pipeline {
    agent any
    tools {
        jdk 'jdk8'
    }
    stages {
        stage('test java installation') {
            steps {
                bat 'java -version'
            }
        }
        stage('Sonarqube') {
            environment {
                scannerHome = tool 'SonarQubeScanner'
            }
            steps {
                withSonarQubeEnv('sonarqube') {
                    bat "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
    }
}